### ISSUE TITLE
如果发生写入错误，只会返回bool而不会返回错误信息

### ISSUE THREAD

**Issue by lxepoo** [lloydzhou/activerecord#1]
如果发生写入错误，只会返回bool而不会返回错误信息，如何帮助开发者完成排错及修改呢？

**Comment by lxepoo** [comment]
问题的关键是你的execute是静态方法，甚至无法在执行前纪录一下本次请求所执行的SQL语句。给debug带来了很多的困难。

**Comment by lloydzhou** [comment]
其实这个execute是调用的PDOStatement::execute确实只能返回bool值代表成功或者失败。
由于这个库相对独立，不依赖其他的东西，所以也没有相应的log之类的，确实调试起来困难！！！

**Comment by lloydzhou** [comment]
你有什么比较好的思路处理这个问题吗？可以提pull request

**Comment by lloydzhou** [comment]
a817a5f 这个提交里面增加了一个打印log的函数，默认采用系统的error_log函数，通常会打印控制台，也能通过自定义设置回调函数来输出到文件等。
设置log处理函数：
ActiveRecord::log(function($message){ ... })

输出错误log消息如下所示：
SQLSTATE [HY000] Code [1] Message [near "(": syntax error]

**Comment by lxepoo** [comment]
好的，我如果完善的话会提交到你的仓库的，感谢！~

**Comment by lloydzhou** [comment]
http://php.net/manual/zh/pdo.error-handling.php
PDO 提供了三种不同的错误处理模式，以满足不同风格的应用开发：

PDO::ERRMODE_SILENT

此为默认模式。 PDO 将只简单地设置错误码，可使用 PDO::errorCode() 和 PDO::errorInfo() 方法来检查语句和数据库对象。如果错误是由于对语句对象的调用而产生的，那么可以调用那个对象的 PDOStatement::errorCode() 或 PDOStatement::errorInfo() 方法。如果错误是由于调用数据库对象而产生的，那么可以在数据库对象上调用上述两个方法。

PDO::ERRMODE_WARNING

除设置错误码之外，PDO 还将发出一条传统的 E_WARNING 信息。如果只是想看看发生了什么问题且不中断应用程序的流程，那么此设置在调试/测试期间非常有用。

PDO::ERRMODE_EXCEPTION

除设置错误码之外，PDO 还将抛出一个 PDOException 异常类并设置它的属性来反射错误码和错误信息。此设置在调试期间也非常有用，因为它会有效地放大脚本中产生错误的点，从而可以非常快速地指出代码中有问题的潜在区域（记住：如果异常导致脚本终止，则事务被自动回滚）。

异常模式另一个非常有用的是，相比传统 PHP 风格的警告，可以更清晰地构建自己的错误处理，而且比起静默模式和显式地检查每种数据库调用的返回值，异常模式需要的代码/嵌套更少。

**Comment by lloydzhou** [comment]
所以，我把之前加上的error这个函数又去掉了，需要handler错误信息的时候，直接在new PDO对象的时候就可以直接指定PDO::ATTR_ERRMODE：

      ActiveRecord::setDb(new PDO('sqlite:test.db', null, null, array(
          PDO::ATTR_ERRMO    DE=>PDO::ERRMODE_EXCEPTION
      )));
或者setDb之后使用以下语句进行设定也是一样的：

      ActiveRecord::$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

都能在出错的时候抛出一个PDOException，当然也可以设定PDO::ERRMODE_WARNING，默认情况下PDO::ERRMODE_SILENT不会打印错误日志也不会抛出异常。
